[[redirects]]
  from = "/audit"
  to = "/audit.html"
  status = 200

[[redirects]]
  from = "/mothership"
  to = "/mothership.html"
  status = 200

[[redirects]]
  from = "/aiden"
  to = "/aiden.html"
  status = 200

[[redirects]]
  from = "/case-studies/mother-london"
  to = "/case-studies/mother-london.html"
  status = 200

[[redirects]]
  from = "/case-studies/uncommon"
  to = "/case-studies/uncommon.html"
  status = 200

[[redirects]]
  from = "/case-studies/alt-shift"
  to = "/case-studies/alt-shift.html"
  status = 200

[[redirects]]
  from = "/case-studies/monigle"
  to = "/case-studies/monigle.html"
  status = 200

[[redirects]]
  from = "/case-studies/collinson"
  to = "/case-studies/collinson.html"
  status = 200

[[redirects]]
  from = "/the-memo"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/the-memo.html"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
